export type ApiSession={accessToken:string;refreshToken:string;expiresIn?:number;organisation:{id:string;name:string;type:string};roles:string[]};
const base=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
const key='adgeco.session';
export function readSession():ApiSession|null{if(typeof window==='undefined')return null;const raw=window.localStorage.getItem(key);if(!raw)return null;try{return JSON.parse(raw) as ApiSession}catch{window.localStorage.removeItem(key);return null}}
export function saveSession(session:ApiSession){window.localStorage.setItem(key,JSON.stringify(session));}
export function clearSession(){if(typeof window!=='undefined')window.localStorage.removeItem(key);}
async function refresh(session:ApiSession):Promise<ApiSession|null>{const response=await fetch(`${base}/v1/auth/refresh`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refreshToken:session.refreshToken})});if(!response.ok){clearSession();return null}const tokens=await response.json() as {accessToken:string;refreshToken:string;expiresIn:number};const next={...session,...tokens};saveSession(next);return next;}
export async function api<T>(path:string,options:RequestInit={},retry=true):Promise<T>{let session=readSession();const request=()=>fetch(`${base}${path}`,{...options,headers:{...(options.body?{'content-type':'application/json'}:{}),...(session?{authorization:`Bearer ${session.accessToken}`}:{}) ,...options.headers}});let response=await request();if(response.status===401&&session&&retry){session=await refresh(session);if(session)response=await request();}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(String(body.code??`HTTP_${response.status}`));}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
export async function logout(){try{await api<void>('/v1/auth/logout',{method:'POST'},false)}finally{clearSession();if(typeof window!=='undefined')window.location.href='/login'}}
