
import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { prisma, Prisma } from '@adgeco/database';
import { tenantRoles, type TenantRole } from '@adgeco/contracts';
import { signAccessSession, signMfaChallenge, verifySession } from '../auth/session.js';
import { assertTenant, authorise, decryptSecret, encryptSecret, generateTotpSecret, hashPassword, hashToken, randomToken, verifyPassword, verifyTotp } from '@adgeco/auth';
import { config, email, role, orgType, tokenHash, deliveryToken, verifyDeliveryToken, deliveryBearer, bearer, context, rolesFor, audit, event, issueSession } from '../shared.js';

export const advertisersRoutes: FastifyPluginAsync = async (app) => {
const advertiserProfileBody=z.object({legalName:z.string().min(2).max(160),tradingName:z.string().min(2).max(160).optional(),website:z.string().url().optional(),countryCode:z.string().length(2),registrationNumber:z.string().max(80).optional(),industry:z.string().min(2).max(100)});
app.put('/v1/advertisers/:organisationId/profile',async(req)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'advertiser:manage');const body=advertiserProfileBody.parse(req.body);const profile=await prisma.advertiserProfile.upsert({where:{organisationId},create:{organisationId,...body,countryCode:body.countryCode.toUpperCase(),status:'ACTIVE'},update:{...body,countryCode:body.countryCode.toUpperCase()}});await event('AdvertiserProfileUpdated',organisationId,{advertiserProfileId:profile.id},req.id);return profile;});
app.get('/v1/advertisers/:organisationId/profile',async(req)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'advertiser:read');return prisma.advertiserProfile.findUnique({where:{organisationId}});});
app.put('/v1/advertisers/:organisationId/billing-profile',async(req)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'advertiser:manage');const body=z.object({billingEmail:z.string().email(),legalName:z.string().min(2),addressLine1:z.string().min(2),addressLine2:z.string().optional(),city:z.string().min(2),region:z.string().optional(),postalCode:z.string().min(2),countryCode:z.string().length(2),currency:z.string().length(3).default('USD'),taxIdentifier:z.string().optional()}).parse(req.body);return prisma.advertiserBillingProfile.upsert({where:{organisationId},create:{organisationId,...body,countryCode:body.countryCode.toUpperCase(),currency:body.currency.toUpperCase(),taxIdentifierEncrypted:body.taxIdentifier?encryptSecret(body.taxIdentifier,config.tokenPepper):undefined,status:'PENDING_VERIFICATION'},update:{...body,countryCode:body.countryCode.toUpperCase(),currency:body.currency.toUpperCase(),taxIdentifierEncrypted:body.taxIdentifier?encryptSecret(body.taxIdentifier,config.tokenPepper):undefined,status:'PENDING_VERIFICATION'}});});
app.post('/v1/advertisers/:organisationId/wallet/fund',async(req,reply)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'wallet:fund');const body=z.object({amount:z.coerce.number().positive(),currency:z.string().length(3).default('USD'),providerReference:z.string().min(3),idempotencyKey:z.string().min(8)}).parse(req.body);const existing=await prisma.walletTransaction.findUnique({where:{idempotencyKey:body.idempotencyKey}});if(existing)return existing;const result=await prisma.$transaction(async tx=>{const wallet=await tx.advertiserWallet.upsert({where:{organisationId},create:{organisationId,currency:body.currency.toUpperCase()},update:{}});const transaction=await tx.walletTransaction.create({data:{walletId:wallet.id,type:'FUNDING',amount:body.amount,currency:body.currency.toUpperCase(),providerReference:body.providerReference,idempotencyKey:body.idempotencyKey,description:'Advertiser wallet funding'}});await tx.advertiserWallet.update({where:{id:wallet.id},data:{availableBalance:{increment:body.amount},lifetimeFunded:{increment:body.amount}}});await tx.outboxEvent.create({data:{organisationId,type:'AdvertiserFunded',correlationId:req.id,payload:{walletId:wallet.id,transactionId:transaction.id,amount:body.amount,currency:body.currency.toUpperCase()}}});return transaction;});return reply.code(201).send(result);});
app.get('/v1/advertisers/:organisationId/wallet',async(req)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'advertiser:read');return prisma.advertiserWallet.findUnique({where:{organisationId},include:{transactions:{orderBy:{createdAt:'desc'},take:50}}});});

const campaignBody=z.object({name:z.string().min(2),objective:z.string().min(2),currency:z.string().length(3).default('USD'),totalBudget:z.coerce.number().positive(),dailyBudget:z.coerce.number().positive().optional(),startAt:z.coerce.date(),endAt:z.coerce.date(),pacingMode:z.enum(['EVEN','ACCELERATED','ASAP']).default('EVEN')}).refine(v=>v.endAt>v.startAt,{message:'endAt must be after startAt'});
app.post('/v1/advertisers/:organisationId/campaigns',async(req,reply)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'campaign:manage');const body=campaignBody.parse(req.body);const wallet=await prisma.advertiserWallet.findUnique({where:{organisationId}});if(!wallet||Number(wallet.availableBalance)<body.totalBudget)return reply.code(409).send({code:'INSUFFICIENT_WALLET_BALANCE'});const campaign=await prisma.campaign.create({data:{organisationId,...body,currency:body.currency.toUpperCase()}});await event('CampaignCreated',organisationId,{campaignId:campaign.id},req.id);return reply.code(201).send(campaign);});
app.get('/v1/advertisers/:organisationId/campaigns',async(req)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'advertiser:read');return prisma.campaign.findMany({where:{organisationId},include:{lineItems:true,creatives:true},orderBy:{createdAt:'desc'}});});
app.post('/v1/campaigns/:campaignId/line-items',async(req,reply)=>{const ctx=await context(req);const {campaignId}=z.object({campaignId:z.string().uuid()}).parse(req.params);const campaign=await prisma.campaign.findUnique({where:{id:campaignId}});if(!campaign)return reply.code(404).send({code:'CAMPAIGN_NOT_FOUND'});assertTenant(ctx,campaign.organisationId);authorise(ctx,'campaign:manage');const body=z.object({name:z.string().min(2),bidAmount:z.coerce.number().positive(),bidStrategy:z.enum(['CPM','CPC','CPA','CPV']),budget:z.coerce.number().positive(),dailyBudget:z.coerce.number().positive().optional(),pacingMode:z.enum(['EVEN','ACCELERATED','ASAP']).default('EVEN'),targeting:z.object({countries:z.array(z.string().length(2)).default([]),deviceTypes:z.array(z.string()).default([]),channels:z.array(z.string()).default([]),languages:z.array(z.string()).default([]),categories:z.array(z.string()).default([])}),frequencyCap:z.object({impressions:z.number().int().positive(),windowHours:z.number().int().positive()}).optional()}).parse(req.body);return reply.code(201).send(await prisma.lineItem.create({data:{campaignId,...body,targeting:{...body.targeting,countries:body.targeting.countries.map(v=>v.toUpperCase())}}}));});
app.post('/v1/advertisers/:organisationId/creatives',async(req,reply)=>{const ctx=await context(req);const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,organisationId);authorise(ctx,'creative:manage');const body=z.object({campaignId:z.string().uuid().optional(),name:z.string().min(2),type:z.enum(['IMAGE','VIDEO','HTML','NATIVE']),assetUrl:z.string().url(),mimeType:z.string().min(3),width:z.number().int().positive().optional(),height:z.number().int().positive().optional(),durationSeconds:z.number().int().positive().optional(),clickThroughUrl:z.string().url(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(req.body);if(body.campaignId){const campaign=await prisma.campaign.findFirst({where:{id:body.campaignId,organisationId}});if(!campaign)return reply.code(404).send({code:'CAMPAIGN_NOT_FOUND'});}const creative=await prisma.creative.create({data:{organisationId,...body,metadata:body.metadata as Prisma.InputJsonValue,status:'PENDING_REVIEW'}});await event('CreativeSubmitted',organisationId,{creativeId:creative.id},req.id);return reply.code(201).send(creative);});
app.post('/v1/admin/creatives/:creativeId/review',async(req,reply)=>{const ctx=await context(req);authorise(ctx,'creative:review');const {creativeId}=z.object({creativeId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['APPROVED','REJECTED','NEEDS_CHANGES']),reason:z.string().max(1000).optional()}).parse(req.body);const creative=await prisma.creative.findUnique({where:{id:creativeId}});if(!creative)return reply.code(404).send({code:'CREATIVE_NOT_FOUND'});const status=body.decision==='APPROVED'?'APPROVED':'REJECTED';const result=await prisma.$transaction(async tx=>{await tx.creativeReview.create({data:{creativeId,reviewerUserId:ctx.actorId,decision:body.decision,reason:body.reason}});return tx.creative.update({where:{id:creativeId},data:{status}});});await event('CreativeReviewed',creative.organisationId,{creativeId,decision:body.decision},req.id);return result;});
app.post('/v1/admin/campaigns/:campaignId/decision',async(req,reply)=>{const ctx=await context(req);authorise(ctx,'campaign:approve');const {campaignId}=z.object({campaignId:z.string().uuid()}).parse(req.params);const body=z.object({decision:z.enum(['APPROVED','REJECTED']),reason:z.string().max(1000).optional()}).parse(req.body);const campaign=await prisma.campaign.findUnique({where:{id:campaignId},include:{creatives:true,lineItems:true}});if(!campaign)return reply.code(404).send({code:'CAMPAIGN_NOT_FOUND'});if(body.decision==='APPROVED'&&(!campaign.creatives.some(c=>c.status==='APPROVED')||campaign.lineItems.length===0))return reply.code(409).send({code:'CAMPAIGN_NOT_READY'});const updated=await prisma.campaign.update({where:{id:campaignId},data:{status:body.decision,approvalReason:body.reason,approvedByUserId:ctx.actorId,approvedAt:new Date()}});await event('CampaignApprovalDecided',campaign.organisationId,{campaignId,decision:body.decision},req.id);return updated;});
app.post('/v1/campaigns/:campaignId/activate',async(req,reply)=>{const ctx=await context(req);const {campaignId}=z.object({campaignId:z.string().uuid()}).parse(req.params);const campaign=await prisma.campaign.findUnique({where:{id:campaignId}});if(!campaign)return reply.code(404).send({code:'CAMPAIGN_NOT_FOUND'});assertTenant(ctx,campaign.organisationId);authorise(ctx,'campaign:manage');if(campaign.status!=='APPROVED'&&campaign.status!=='PAUSED')return reply.code(409).send({code:'CAMPAIGN_NOT_APPROVED'});const updated=await prisma.campaign.update({where:{id:campaignId},data:{status:'ACTIVE'}});await event('CampaignActivated',campaign.organisationId,{campaignId},req.id);return updated;});
app.post('/v1/campaigns/:campaignId/pause',async(req,reply)=>{const ctx=await context(req);const {campaignId}=z.object({campaignId:z.string().uuid()}).parse(req.params);const campaign=await prisma.campaign.findUnique({where:{id:campaignId}});if(!campaign)return reply.code(404).send({code:'CAMPAIGN_NOT_FOUND'});assertTenant(ctx,campaign.organisationId);authorise(ctx,'campaign:manage');return prisma.campaign.update({where:{id:campaignId},data:{status:'PAUSED'}});});
app.get('/v1/advertisers/:organisationId/dashboard',async(req)=>{
  const ctx=await context(req);
  const {organisationId}=z.object({organisationId:z.string().uuid()}).parse(req.params);
  
  assertTenant(ctx,organisationId);
  authorise(ctx,'advertiser:read');
  
  const [profile,billing,wallet,campaigns,creatives,lineItems]=await Promise.all([
    prisma.advertiserProfile.findUnique({where:{organisationId}}),
    prisma.advertiserBillingProfile.findUnique({where:{organisationId},select:{status:true,currency:true,billingEmail:true}}),
    prisma.advertiserWallet.findUnique({where:{organisationId}}),
    prisma.campaign.findMany({where:{organisationId},select:{id:true,name:true,status:true,totalBudget:true,dailyBudget:true,startAt:true,endAt:true}}),
    prisma.creative.findMany({where:{organisationId},select:{id:true,name:true,status:true}}),
    prisma.lineItem.count({where:{campaign:{organisationId}}})
  ]);
  
  return {
    profile,
    billing,
    wallet,
    metrics:{
      campaigns:campaigns.length,
      activeCampaigns:campaigns.filter(c=>c.status==='ACTIVE').length,
      creatives:creatives.length,
      lineItems
    },
    campaigns,
    creatives
  };
});
};
