
import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { prisma, Prisma } from '@adgeco/database';
import { tenantRoles, type TenantRole } from '@adgeco/contracts';
import { signAccessSession, signMfaChallenge, verifySession } from '../auth/session.js';
import { assertTenant, authorise, decryptSecret, encryptSecret, generateTotpSecret, hashPassword, hashToken, randomToken, verifyPassword, verifyTotp } from '@adgeco/auth';
import { config, email, role, orgType, tokenHash, deliveryToken, verifyDeliveryToken, deliveryBearer, bearer, context, rolesFor, audit, event, issueSession } from '../shared.js';

export const organisationsRoutes: FastifyPluginAsync = async (app) => {
app.post('/v1/organisations',async(req,reply)=>{ const ctx=await context(req); const body=z.object({name:z.string().min(2),type:orgType}).parse(req.body); const ownerRole=`${body.type}_OWNER`; const organisation=await prisma.$transaction(async(tx)=>{const org=await tx.organisation.create({data:{name:body.name,type:body.type,slug:`${body.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,48)}-${randomToken(4).toLowerCase()}`}});await tx.organisationMembership.create({data:{userId:ctx.actorId,organisationId:org.id,role:ownerRole,status:'ACTIVE'}});return org;}); return reply.code(201).send(organisation); });
app.get('/v1/organisations/:organisationId/members',async(req)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'organisation:read');return prisma.organisationMembership.findMany({where:{organisationId:params.organisationId},select:{id:true,role:true,status:true,createdAt:true,user:{select:{id:true,email:true,emailVerifiedAt:true}}}});});
app.post('/v1/organisations/:organisationId/invitations',async(req,reply)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'membership:invite');const body=z.object({email,role}).parse(req.body);const invitationToken=randomToken();const invitation=await prisma.organisationInvitation.create({data:{organisationId:params.organisationId,email:body.email,role:body.role,tokenHash:tokenHash(invitationToken),invitedByUserId:ctx.actorId,expiresAt:new Date(Date.now()+7*24*60*60*1000)}});await event('OrganisationInvitationCreated',params.organisationId,{invitationId:invitation.id,email:body.email,role:body.role,invitationTokenEncrypted:encryptSecret(invitationToken,config.tokenPepper)},req.id);return reply.code(201).send({id:invitation.id,email:invitation.email,role:invitation.role,expiresAt:invitation.expiresAt,...(config.nodeEnv==='production'?{}:{developmentInvitationToken:invitationToken})});});
app.post('/v1/invitations/accept',async(req,reply)=>{const ctx=await context(req);const body=z.object({token:z.string()}).parse(req.body);const invitation=await prisma.organisationInvitation.findFirst({where:{tokenHash:tokenHash(body.token),status:'PENDING',expiresAt:{gt:new Date()}}});const user=await prisma.user.findUniqueOrThrow({where:{id:ctx.actorId}});if(!invitation||invitation.email!==user.email)return reply.code(400).send({code:'INVALID_INVITATION'});await prisma.$transaction([prisma.organisationMembership.upsert({where:{userId_organisationId_role:{userId:user.id,organisationId:invitation.organisationId,role:invitation.role}},create:{userId:user.id,organisationId:invitation.organisationId,role:invitation.role,status:'ACTIVE'},update:{status:'ACTIVE'}}),prisma.organisationInvitation.update({where:{id:invitation.id},data:{status:'ACCEPTED',acceptedByUserId:user.id,acceptedAt:new Date()}})]);return {accepted:true,organisationId:invitation.organisationId};});

app.post('/v1/organisations/:organisationId/service-accounts',async(req,reply)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'credential:manage');const body=z.object({name:z.string().min(2),description:z.string().max(500).optional(),scopes:z.array(z.string()).min(1),expiresAt:z.coerce.date().optional()}).parse(req.body);const clientId=`svc_${randomToken(12)}`;const secret=randomToken(40);const account=await prisma.serviceAccount.create({data:{organisationId:params.organisationId,name:body.name,description:body.description,clientId,secretHash:tokenHash(secret),scopes:body.scopes,expiresAt:body.expiresAt}});return reply.code(201).send({id:account.id,clientId,clientSecret:secret,scopes:account.scopes,expiresAt:account.expiresAt});});
app.delete('/v1/organisations/:organisationId/service-accounts/:id',async(req,reply)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid(),id:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'credential:manage');await prisma.serviceAccount.updateMany({where:{id:params.id,organisationId:params.organisationId},data:{status:'REVOKED'}});return reply.code(204).send();});
app.post('/v1/organisations/:organisationId/api-credentials',async(req,reply)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'credential:manage');const body=z.object({name:z.string().min(2),scopes:z.array(z.string()).min(1),expiresAt:z.coerce.date().optional()}).parse(req.body);const prefix=`adg_${randomToken(6)}`;const secret=randomToken(32);const fullKey=`${prefix}.${secret}`;const key=await prisma.apiCredential.create({data:{organisationId:params.organisationId,name:body.name,prefix,keyHash:tokenHash(fullKey),scopes:body.scopes,expiresAt:body.expiresAt,createdByUserId:ctx.actorId}});return reply.code(201).send({id:key.id,key:fullKey,prefix,scopes:key.scopes,expiresAt:key.expiresAt});});
app.delete('/v1/organisations/:organisationId/api-credentials/:id',async(req,reply)=>{const ctx=await context(req);const params=z.object({organisationId:z.string().uuid(),id:z.string().uuid()}).parse(req.params);assertTenant(ctx,params.organisationId);authorise(ctx,'credential:manage');await prisma.apiCredential.updateMany({where:{id:params.id,organisationId:params.organisationId},data:{status:'REVOKED',revokedAt:new Date()}});return reply.code(204).send();});
};
