import { createHash } from 'node:crypto';
export * from './provider-runtime.mjs';
const requireInt=(v,n)=>{if(!Number.isSafeInteger(v))throw new Error(`${n}_MUST_BE_SAFE_INTEGER`);return v};
export function evaluateConsent({jurisdiction,personalisedAds,consentString,doNotSell=false,ageRestricted=false}){
 const regulated=['GB','EU','EEA','US-CA','US-CO','US-CT','US-VA'].includes(jurisdiction);
 if(ageRestricted&&personalisedAds)return {allowed:false,mode:'CONTEXTUAL',reason:'AGE_RESTRICTED'};
 if(doNotSell&&personalisedAds)return {allowed:false,mode:'CONTEXTUAL',reason:'OPT_OUT'};
 if(regulated&&personalisedAds&&!consentString)return {allowed:false,mode:'CONTEXTUAL',reason:'CONSENT_REQUIRED'};
 return {allowed:true,mode:personalisedAds?'PERSONALISED':'CONTEXTUAL',reason:'POLICY_SATISFIED'};
}
export function calculateTax({amountMinor,rateBasisPoints,inclusive=false}){requireInt(amountMinor,'AMOUNT');requireInt(rateBasisPoints,'RATE');if(amountMinor<0||rateBasisPoints<0||rateBasisPoints>10000)throw new Error('INVALID_TAX_INPUT');const taxMinor=inclusive?Math.round(amountMinor*rateBasisPoints/(10000+rateBasisPoints)):Math.round(amountMinor*rateBasisPoints/10000);return {netMinor:inclusive?amountMinor-taxMinor:amountMinor,taxMinor,grossMinor:inclusive?amountMinor:amountMinor+taxMinor};}
export function paceBudget({budgetMinor,spentMinor,reservedMinor,elapsedRatio,mode='EVEN',tolerance=0.1}){[budgetMinor,spentMinor,reservedMinor].forEach((v,i)=>requireInt(v,['BUDGET','SPENT','RESERVED'][i]));if(budgetMinor<=0||elapsedRatio<0||elapsedRatio>1)throw new Error('INVALID_PACING_INPUT');const committed=spentMinor+reservedMinor;const target=mode==='ASAP'?budgetMinor:Math.round(budgetMinor*Math.min(1,elapsedRatio*(mode==='ACCELERATED'?1.25:1)));const allowance=Math.max(0,Math.round(target*(1+tolerance))-committed);return {eligible:allowance>0,allowanceMinor:Math.min(allowance,budgetMinor-committed),committedMinor:committed,targetMinor:target};}
export function frequencyCapDecision({exposures,limit,windowStartedAt,windowSeconds,now=Date.now()}){requireInt(exposures,'EXPOSURES');requireInt(limit,'LIMIT');requireInt(windowSeconds,'WINDOW_SECONDS');const expired=now-new Date(windowStartedAt).getTime()>=windowSeconds*1000;const current=expired?0:exposures;return {allowed:current<limit,nextCount:current<limit?current+1:current,resetAt:new Date((expired?now:new Date(windowStartedAt).getTime())+windowSeconds*1000).toISOString()};}
export function brandSafetyDecision({categories=[],blockedCategories=[],pageText=''}){const normalized=new Set(categories.map(v=>v.toLowerCase()));const keywordHits=blockedCategories.filter(v=>normalized.has(v.toLowerCase())||pageText.toLowerCase().includes(v.toLowerCase()));return {allowed:keywordHits.length===0,reasons:keywordHits};}
export function payoutTransition(current,event){const map={PENDING:{SUBMIT:'SUBMITTED',FAIL:'FAILED'},SUBMITTED:{SUCCEED:'SUCCEEDED',FAIL:'FAILED'},FAILED:{RETRY:'RETRY_SCHEDULED'},RETRY_SCHEDULED:{SUBMIT:'SUBMITTED'}};const next=map[current]?.[event];if(!next)throw new Error(`INVALID_PAYOUT_TRANSITION:${current}:${event}`);return next;}
export function reconciliationDecision({internalMinor,providerMinor,toleranceMinor=0}){[internalMinor,providerMinor,toleranceMinor].forEach((v,i)=>requireInt(v,['INTERNAL','PROVIDER','TOLERANCE'][i]));const varianceMinor=providerMinor-internalMinor;return {status:Math.abs(varianceMinor)<=toleranceMinor?'MATCHED':'EXCEPTION',varianceMinor};}
export function stableIdempotencyKey(namespace,payload){return `${namespace}_${createHash('sha256').update(JSON.stringify(payload,Object.keys(payload).sort())).digest('hex')}`;}
